version: '3'
services:
  web:
  #  image: gerrome/mevn-stack-app_web:1
   build: .
   ports:
      - "3000:3000"
   env_file: ./.env	   
   depends_on:
      - "mongo"    

  client:
  #  image: gerrome/mevn-stack-app_client:1
    build: 
      context: ./client
    ports:
      - 8080:8080

  mongo:
    image: mongo:4.4
    ports: 
      - 27017:27017
    env_file: ./.env
    environment:
      - MONGO-INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO-INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGODB_URI=$MONGO_URI
    stdin_open: true

  nginx:
    build: ./nginx
    ports: 
      - 80:80
    depends_on:
      - client
